tasks:
  - init: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
  - init: touch .env && echo API_TOKEN = abcd >> .env
  - init: yarn install && yarn run build
    command: yarn run dev

ports:
  - port: 5173
    onOpen: open-preview
    name: Website

vscode:
  extensions:
    - svelte.svelte-vscode
    - dbaeumer.vscode-eslint
