
tasks:
  - init: sudo yarn playwright install-deps
  - init: yarn playwright install
  - init: yarn install && yarn run build
    command: yarn run dev

ports:
  - port: 5173
    onOpen: open-preview
    name: Website

vscode:
  extensions:
    - svelte.svelte-vscode
    - dbaeumer.vscode-eslint
