name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependancies
        run: yarn

      - name: Check Formatting
        run: yarn format-check

      - name: Setup dummy env file
        run: |
          touch .env
          echo API_TOKEN = abcd >> .env

      - name: Build server
        run: yarn build

      - name: Run tests
        run: yarn test
